name: Deploy Container App

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-cloudkit-dev-cus
  CONTAINER_APP_NAME: backend-cloudkit-dev-cus
  ACR_SERVER: acrcloudkitdevcus.azurecr.io
  ACR_IMAGE: acrcloudkitdevcus.azurecr.io/cloudkit-backend:latest

jobs:
  configure_containerapp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Wait and check Container App state
        run: |
          echo "🔄 Esperando a que Container App esté completamente provisionado..."
          for i in {1..15}; do
            STATE=$(az containerapp show \
              --name $CONTAINER_APP_NAME \
              --resource-group $RESOURCE_GROUP \
              --query "properties.provisioningState" -o tsv 2>/dev/null)

            if [ -z "$STATE" ]; then
              echo "Estado aún no disponible, reintentando..."
              sleep 10
              continue
            fi

            echo "Intento $i: Estado actual = $STATE"

            if [ "$STATE" == "Succeeded" ]; then
              echo "✅ Container App aprovisionado correctamente."
              break
            fi

            if [ "$STATE" == "Failed" ]; then
              echo "❌ El Container App falló al provisionarse."
              exit 1
            fi

            sleep 10
          done

      - name: Asignar rol AcrPull al Container App
        run: |
          PRINCIPAL_ID=$(az containerapp show \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --query identity.principalId -o tsv)

          ACR_ID=$(az acr show \
            --name acrcloudkitdevcus \
            --query id -o tsv)

          echo "🔐 Asignando rol AcrPull al Container App..."
          az role assignment create \
            --assignee $PRINCIPAL_ID \
            --scope $ACR_ID \
            --role AcrPull

      - name: Configurar acceso al ACR
        run: |
          echo "🔐 Configurando acceso al ACR..."
          az containerapp registry set \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --server $ACR_SERVER \
            --identity system

      - name: Actualizar imagen del Container App
        run: |
          echo "🚀 Actualizando imagen a $ACR_IMAGE"
          az containerapp update \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_IMAGE
