name: Deploy Web App Frontend

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-cloudkit-dev-cus
  WEBAPP_NAME: frontend-cloudkit-dev-cus
  ACR_SERVER: acrcloudkitdevcus.azurecr.io
  ACR_IMAGE: acrcloudkitdevcus.azurecr.io/cloudkit-frontend:latest

jobs:
  deploy_webapp:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Asignar rol AcrPull al Web App
        run: |
          PRINCIPAL_ID=$(az webapp show \
            --name $WEBAPP_NAME \
            --resource-group $RESOURCE_GROUP \
            --query identity.principalId -o tsv)

          ACR_ID=$(az acr show \
            --name acrcloudkitdevcus \
            --query id -o tsv)

          echo "🔐 Asignando rol AcrPull..."
          az role assignment create \
            --assignee $PRINCIPAL_ID \
            --scope $ACR_ID \
            --role AcrPull || true

      - name: Actualizar imagen del Web App
        run: |
          echo "🚀 Actualizando imagen a $ACR_IMAGE"
          az webapp config container set \
            --name $WEBAPP_NAME \
            --resource-group $RESOURCE_GROUP \
            --docker-custom-image-name $ACR_IMAGE \
            --docker-registry-server-url https://$ACR_SERVER
